spring:
  application:
    name: PickTrip

  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 배포 시에는 Validate로 변경.
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time-ms: 1800000    # 30분
  refresh-token-expire-time-days: 14      # 14일

app:
  cors:
    allowed-origins: http://localhost:3000