spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}


public-data-portal:
  key:
    encode: ${PUBLIC_DATA_PORTAL_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time: 3600000   # 1시간 (ms)
  refresh-token-expire-time: 14       # 14일 (days)

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

app:
  cors:
    allowed-origins: http://localhost:3000
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI}

tour-api:
  base-url: base-url
  photo-base-url: https://apis.data.go.kr/B551011/PhotoGalleryService1
  service-key: ${PUBLIC_DATA_PORTAL_KEY}