spring:
  application:
    name: PickTrip

  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 배포 시에는 Validate로 변경.
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

app:
  cors:
    allowed-origins: http://localhost:3000